services:
  Weather-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Weather-web-app
    ports:
      - 3000:3000 # map host port with container port
    restart: "unless-stopped"